// <auto-generated />
using System;
using GauntletCI.Watchtower.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GauntletCI.Watchtower.Migrations
{
    [DbContext(typeof(WatchtowerDbContext))]
    [Migration("20260501093304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("ConfidenceScores")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GauntletVersionTested")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesFired")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.ArticleDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ArticleDrafts");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.CVE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("CvssScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FirstSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CveId")
                        .IsUnique();

                    b.ToTable("CVEs");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.CVEFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PollingIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CVEFeeds");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.CVEFeedEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvisoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CVEId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("CvssScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FeedId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeverityRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CVEId");

                    b.HasIndex("FeedId", "CveId")
                        .IsUnique();

                    b.ToTable("CVEFeedEntries");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.GauntletRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BuildSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BuildTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("CliArtifactPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GauntletRuns");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.Miss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonForMiss")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedRuleEnhancements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Misses");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.TechnicalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedVersions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedRepositoryUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VulnerabilityClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CveId")
                        .IsUnique();

                    b.ToTable("TechnicalData");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.ValidationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturedDiff")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CveId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetectionOccurred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StderrPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StdoutPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CveId");

                    b.HasIndex("ValidationRunId");

                    b.ToTable("ValidationResults");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.ValidationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticlesDrafted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticlesPublished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Detected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GauntletRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Missed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NonAnalyzable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalAnalyzed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GauntletRunId");

                    b.ToTable("ValidationRuns");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.CVEFeedEntry", b =>
                {
                    b.HasOne("GauntletCI.Watchtower.Models.Entities.CVE", "CVE")
                        .WithMany()
                        .HasForeignKey("CVEId");

                    b.HasOne("GauntletCI.Watchtower.Models.Entities.CVEFeed", "Feed")
                        .WithMany("Entries")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CVE");

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.TechnicalData", b =>
                {
                    b.HasOne("GauntletCI.Watchtower.Models.Entities.CVE", "CVE")
                        .WithOne("TechnicalData")
                        .HasForeignKey("GauntletCI.Watchtower.Models.Entities.TechnicalData", "CveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CVE");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.ValidationResult", b =>
                {
                    b.HasOne("GauntletCI.Watchtower.Models.Entities.CVE", "CVE")
                        .WithMany("ValidationResults")
                        .HasForeignKey("CveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GauntletCI.Watchtower.Models.Entities.ValidationRun", "ValidationRun")
                        .WithMany("Results")
                        .HasForeignKey("ValidationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CVE");

                    b.Navigation("ValidationRun");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.ValidationRun", b =>
                {
                    b.HasOne("GauntletCI.Watchtower.Models.Entities.GauntletRun", "GauntletRun")
                        .WithMany()
                        .HasForeignKey("GauntletRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GauntletRun");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.CVE", b =>
                {
                    b.Navigation("TechnicalData");

                    b.Navigation("ValidationResults");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.CVEFeed", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("GauntletCI.Watchtower.Models.Entities.ValidationRun", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
