import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import {
  AlertTriangle,
  ArrowRight,
  Code2,
  FileJson,
  GitPullRequest,
  ShieldCheck,
} from "lucide-react";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Breadcrumbs } from "@/components/breadcrumbs";

const checksWorkflow = `name: GauntletCI Checks

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write

jobs:
  gauntletci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Install GauntletCI
        run: dotnet tool install -g GauntletCI --version 2.1.1

      - name: Post GitHub Checks annotations
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: \${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          gauntletci analyze \\
            --commit "$GITHUB_SHA" \\
            --no-llm \\
            --github-checks`;

const sarifWorkflow = `name: GauntletCI SARIF

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  gauntletci-sarif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Install GauntletCI
        run: dotnet tool install -g GauntletCI --version 2.1.1

      - name: Generate SARIF
        run: |
          gauntletci analyze \\
            --commit "\${{ github.event.pull_request.head.sha || github.sha }}" \\
            --no-llm \\
            --output gauntletci.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gauntletci.sarif
          category: gauntletci`;

const sarifExample = `{
  "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
  "version": "2.1.0",
  "runs": [{
    "tool": {
      "driver": {
        "name": "GauntletCI",
        "rules": [{
          "id": "GCI0012",
          "name": "SecurityRisk",
          "shortDescription": { "text": "Security Risk" },
          "helpUri": "https://gauntletci.com/docs/rules/GCI0012"
        }]
      }
    },
    "results": [{
      "ruleId": "GCI0012",
      "level": "error",
      "message": {
        "text": "Authorization logic changed on a protected endpoint. Action: keep authorization checks outside optional branches."
      },
      "locations": [{
        "physicalLocation": {
          "artifactLocation": { "uri": "src/Orders/OrderController.cs" },
          "region": { "startLine": 87 }
        }
      }]
    }]
  }]
}`;

export const metadata: Metadata = {
  title: "GitHub Checks and SARIF Preview | GauntletCI Demo",
  description:
    "Preview how GauntletCI findings can appear as GitHub Checks annotations and SARIF code scanning alerts using direct CLI workflows.",
  alternates: { canonical: "/demo/github-checks-sarif" },
  openGraph: {
    title: "GauntletCI GitHub Checks and SARIF Preview",
    description:
      "Reference preview for GitHub Checks annotations, SARIF output, and code scanning alert workflows.",
    url: "https://gauntletci.com/demo/github-checks-sarif",
    images: [
      {
        url: "/og/github-checks-sarif.png",
        width: 1200,
        height: 630,
        alt: "GauntletCI GitHub Checks and SARIF Preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "GauntletCI GitHub Checks and SARIF Preview",
    description:
      "See what GauntletCI findings look like in GitHub Checks and SARIF-compatible code scanning tools.",
    images: ["/og/github-checks-sarif.png"],
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "TechArticle",
  headline: "GauntletCI GitHub Checks and SARIF Preview",
  description:
    "A static preview of GitHub Checks annotations and SARIF output generated by GauntletCI CLI workflows.",
  url: "https://gauntletci.com/demo/github-checks-sarif",
  publisher: { "@type": "Organization", name: "GauntletCI", url: "https://gauntletci.com" },
};

function StatusPill({ children, tone }: { children: ReactNode; tone: "red" | "yellow" | "green" | "cyan" }) {
  const tones = {
    red: "border-red-500/30 bg-red-500/10 text-red-400",
    yellow: "border-yellow-500/30 bg-yellow-500/10 text-yellow-400",
    green: "border-emerald-500/30 bg-emerald-500/10 text-emerald-400",
    cyan: "border-cyan-500/30 bg-cyan-500/10 text-cyan-400",
  };

  return (
    <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-semibold ${tones[tone]}`}>
      {children}
    </span>
  );
}

function CodeBlock({ code }: { code: string }) {
  return (
    <div className="overflow-x-auto rounded-xl border border-border bg-zinc-950 p-4">
      <pre className="text-xs leading-relaxed text-zinc-200 whitespace-pre">{code}</pre>
    </div>
  );
}

export default function GitHubChecksSarifPreviewPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <Header />
      <main className="min-h-screen bg-background pt-24">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 py-16 sm:py-20 space-y-16">
          <Breadcrumbs />

          <section className="grid gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">
            <div className="space-y-6">
              <div className="inline-flex items-center gap-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-4 py-1.5 text-sm text-muted-foreground">
                <GitPullRequest className="h-4 w-4 text-cyan-400" />
                Static preview, copyable workflows
              </div>
              <div className="space-y-4">
                <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-balance">
                  Preview GauntletCI findings in GitHub Checks and SARIF
                </h1>
                <p className="text-xl text-muted-foreground leading-relaxed text-pretty">
                  See how the same finding can appear in a pull request check run, a line-level
                  annotation, and a SARIF-compatible code scanning view before wiring it into your own
                  repository.
                </p>
              </div>
              <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/10 p-4 text-sm text-yellow-100">
                <p className="font-semibold text-yellow-300">Capability note</p>
                <p className="mt-1 text-yellow-100/80">
                  These advanced outputs are available through direct CLI invocation today. The
                  published composite GitHub Action currently exposes inline PR comments; use the
                  workflows below when you need Checks API annotations or SARIF upload.
                </p>
              </div>
              <div className="flex flex-col gap-3 sm:flex-row">
                <Link
                  href="/demo"
                  className="inline-flex items-center justify-center gap-2 rounded-lg bg-cyan-500 px-5 py-3 text-sm font-semibold text-black hover:bg-cyan-400 transition-colors"
                >
                  Back to live demo
                  <ArrowRight className="h-4 w-4" />
                </Link>
                <Link
                  href="/docs/integrations/github-action"
                  className="inline-flex items-center justify-center gap-2 rounded-lg border border-border bg-card px-5 py-3 text-sm font-semibold hover:bg-card/80 transition-colors"
                >
                  GitHub Action docs
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </div>
            </div>

            <div className="rounded-2xl border border-border bg-card/50 p-6 shadow-2xl shadow-black/20">
              <div className="flex items-center justify-between border-b border-border pb-4">
                <div>
                  <p className="text-sm font-semibold text-foreground">Pull request checks</p>
                  <p className="mt-1 text-xs text-muted-foreground">EricCogen/GauntletCI-Demo #299</p>
                </div>
                <StatusPill tone="red">failing</StatusPill>
              </div>
              <div className="mt-5 space-y-3">
                <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-4">
                  <div className="flex items-start gap-3">
                    <AlertTriangle className="mt-0.5 h-5 w-5 text-red-400" />
                    <div>
                      <p className="font-semibold text-foreground">GauntletCI Risk Analysis</p>
                      <p className="mt-1 text-sm text-muted-foreground">
                        3 grouped findings (2 block, 1 warn)
                      </p>
                    </div>
                  </div>
                </div>
                <div className="rounded-lg border border-border bg-background/60 p-4">
                  <p className="text-xs font-semibold text-cyan-400">GCI0012: Security Risk</p>
                  <p className="mt-2 text-sm text-muted-foreground">
                    Authorization logic changed on a protected endpoint.
                  </p>
                  <p className="mt-2 font-mono text-xs text-muted-foreground">
                    src/Orders/OrderController.cs:87
                  </p>
                </div>
                <div className="rounded-lg border border-border bg-background/60 p-4">
                  <p className="text-xs font-semibold text-cyan-400">GCI0039: External Service Safety</p>
                  <p className="mt-2 text-sm text-muted-foreground">
                    HTTP call added without cancellation flow in a request path.
                  </p>
                  <p className="mt-2 font-mono text-xs text-muted-foreground">
                    src/Billing/PaymentClient.cs:42
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section className="grid gap-6 lg:grid-cols-2">
            <div className="rounded-2xl border border-border bg-card/50 p-6">
              <div className="flex items-center gap-3">
                <ShieldCheck className="h-5 w-5 text-cyan-400" />
                <h2 className="text-2xl font-bold tracking-tight">GitHub Checks API preview</h2>
              </div>
              <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
                The CLI flag <code className="bg-muted px-1 rounded text-xs">--github-checks</code>{" "}
                creates a completed check run with grouped findings and up to 50 line annotations.
                It requires <code className="bg-muted px-1 rounded text-xs">checks: write</code>, a
                repository token, and a GitHub Actions commit SHA.
              </p>
              <div className="mt-5 space-y-3">
                <div className="rounded-lg border border-border bg-background/60 p-4">
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <p className="text-sm font-semibold text-foreground">GauntletCI Risk Analysis</p>
                      <p className="mt-1 text-xs text-muted-foreground">
                        Conclusion: failure when Block findings exist; neutral for Warn-only findings.
                      </p>
                    </div>
                    <StatusPill tone="red">failure</StatusPill>
                  </div>
                </div>
                <div className="rounded-lg border border-border bg-background/60 p-4">
                  <p className="text-xs font-mono text-muted-foreground">annotation</p>
                  <p className="mt-2 text-sm font-semibold text-foreground">
                    GCI0012: Security Risk
                  </p>
                  <p className="mt-1 text-sm text-muted-foreground">
                    Message, evidence, why it matters, and suggested action appear in the check run
                    annotation details.
                  </p>
                </div>
              </div>
            </div>

            <div className="rounded-2xl border border-border bg-card/50 p-6">
              <div className="flex items-center gap-3">
                <FileJson className="h-5 w-5 text-cyan-400" />
                <h2 className="text-2xl font-bold tracking-tight">SARIF/code scanning preview</h2>
              </div>
              <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
                The CLI can write SARIF 2.1.0 with rule IDs, severity levels, messages, and file
                locations. Uploading that file with GitHub&apos;s SARIF action can surface findings in
                SARIF-compatible code scanning tools.
              </p>
              <div className="mt-5 rounded-lg border border-border bg-background/60 p-4">
                <div className="flex items-start gap-3">
                  <Code2 className="mt-0.5 h-5 w-5 text-cyan-400" />
                  <div>
                    <div className="flex flex-wrap items-center gap-2">
                      <StatusPill tone="red">error</StatusPill>
                      <StatusPill tone="cyan">GCI0012</StatusPill>
                    </div>
                    <p className="mt-3 text-sm font-semibold text-foreground">
                      Security Risk in OrderController.cs
                    </p>
                    <p className="mt-1 text-sm text-muted-foreground">
                      Alert payload includes the rule ID, message, level, URI, and start line.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="space-y-6">
            <div>
              <p className="text-sm font-semibold uppercase tracking-widest text-cyan-400">
                Copyable workflows
              </p>
              <h2 className="mt-2 text-3xl font-bold tracking-tight">
                Use direct CLI steps for Checks and SARIF
              </h2>
              <p className="mt-3 max-w-3xl text-sm text-muted-foreground leading-relaxed">
                The composite action is the shortest install path for inline review comments. For
                GitHub Checks API annotations or SARIF upload, call the CLI directly so the workflow can
                pass the required permissions, token, commit SHA, and output file.
              </p>
            </div>

            <div className="grid gap-6 lg:grid-cols-2">
              <div className="space-y-4">
                <div className="flex flex-wrap items-center gap-2">
                  <StatusPill tone="cyan">Checks API</StatusPill>
                  <StatusPill tone="yellow">Teams-tier integration path</StatusPill>
                </div>
                <CodeBlock code={checksWorkflow} />
              </div>
              <div className="space-y-4">
                <div className="flex flex-wrap items-center gap-2">
                  <StatusPill tone="cyan">SARIF</StatusPill>
                  <StatusPill tone="green">standard output format</StatusPill>
                </div>
                <CodeBlock code={sarifWorkflow} />
              </div>
            </div>
          </section>

          <section className="space-y-4">
            <div>
              <p className="text-sm font-semibold uppercase tracking-widest text-cyan-400">
                SARIF shape
              </p>
              <h2 className="mt-2 text-3xl font-bold tracking-tight">
                The preview uses standard SARIF fields
              </h2>
              <p className="mt-3 max-w-3xl text-sm text-muted-foreground leading-relaxed">
                This shortened example shows the structure GauntletCI emits: a tool driver with GCI
                rule metadata, plus result entries with rule IDs, severity levels, messages, and
                source locations.
              </p>
            </div>
            <CodeBlock code={sarifExample} />
          </section>

          <section className="rounded-2xl border border-border bg-card/50 p-6">
            <h2 className="text-2xl font-bold tracking-tight">Next steps</h2>
            <p className="mt-3 max-w-3xl text-sm text-muted-foreground leading-relaxed">
              Start with the public demo PRs, then use the rule docs and configuration docs to decide
              which output surface fits your team&apos;s merge policy.
            </p>
            <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
              {[
                { href: "/demo", label: "Live demo PRs" },
                { href: "/docs/rules", label: "Rule library" },
                { href: "/docs/integrations/github-action", label: "GitHub Action docs" },
                { href: "/docs/configuration", label: "Configuration docs" },
              ].map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className="inline-flex items-center justify-between gap-2 rounded-lg border border-border bg-background px-4 py-3 text-sm font-semibold hover:border-cyan-500/40 hover:bg-card transition-colors"
                >
                  {item.label}
                  <ArrowRight className="h-4 w-4 text-cyan-400" />
                </Link>
              ))}
            </div>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
