// SPDX-License-Identifier: Elastic-2.0
namespace GauntletCI.Core.Model;

/// <summary>An individual risk finding produced by a rule during diff analysis.</summary>
public class Finding
{
    /// <summary>The unique identifier of the rule that produced this finding.</summary>
    public required string RuleId { get; set; }
    /// <summary>The human-readable name of the rule that produced this finding.</summary>
    public required string RuleName { get; set; }
    /// <summary>A short description of the detected risk.</summary>
    public required string Summary { get; set; }
    /// <summary>The file, line, and code snippet that triggered the finding.</summary>
    public required string Evidence { get; set; }       // file + line + snippet
    /// <summary>Explains why this pattern is risky and what can go wrong.</summary>
    public required string WhyItMatters { get; set; }
    /// <summary>Actionable guidance on how to address the finding.</summary>
    public required string SuggestedAction { get; set; }
    /// <summary>The confidence level assigned by the detecting rule.</summary>
    public Confidence Confidence { get; set; }
    /// <summary>
    /// The severity of this finding, determining display and exit-code behavior.
    /// Set by <see cref="GauntletCI.Core.Rules.RuleOrchestrator"/> from the effective
    /// severity resolved by <see cref="GauntletCI.Core.Configuration.ConfigurationService"/>.
    /// </summary>
    public RuleSeverity Severity { get; set; } = RuleSeverity.Info;
    /// <summary>The path of the file that contains the finding, if applicable.</summary>
    public string? FilePath { get; set; }
    /// <summary>The line number within <see cref="FilePath"/> where the finding was detected.</summary>
    public int? Line { get; set; }
    /// <summary>Optional natural-language explanation generated by an LLM enrichment step.</summary>
    public string? LlmExplanation { get; set; }         // optional LLM enrichment
    /// <summary>Optional expert knowledge fact matched against this finding.</summary>
    public ExpertFact? ExpertContext { get; set; }      // optional expert knowledge match
    /// <summary>Optional verbatim code snippet extracted from the diff by an LLM evaluation step.</summary>
    public string? CodeSnippet { get; set; }
}
